### ISSUE TITLE
[Status/BE] Boolean cannot represent a non boolean value: 0

### ISSUE THREAD

**Issue by SeheonYu** [Trapscendence/ft_transcendence#192]
Query:
```
query {
  users(limit: 0, offset: 0, ladder: 0) {
  	status
  }
}
```

Response:
```
{
  "error": {
    "errors": [
      {
        "message": "Boolean cannot represent a non boolean value: 0",
        "locations": [
          {
            "line": 2,
            "column": 38
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Boolean cannot represent a non boolean value: 0",
              "    at GraphQLScalarType.parseLiteral (/app/node_modules/graphql/type/scalars.js:228:13)",
              "    at isValidValueNode (/app/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:125:28)",
              "    at Object.IntValue (/app/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:87:14)",
              "    at Object.enter (/app/node_modules/graphql/language/visitor.js:323:29)",
              "    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:370:25)",
              "    at visit (/app/node_modules/graphql/language/visitor.js:243:26)",
              "    at validate (/app/node_modules/graphql/validation/validate.js:69:24)",
              "    at validate (/app/node_modules/apollo-server-core/src/requestPipeline.ts:458:27)",
              "    at processGraphQLRequest (/app/node_modules/apollo-server-core/src/requestPipeline.ts:245:30)",
              "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by SeheonYu** [comment]
query:
```
query {
  users(limit: 0, offset: 0, ladder: false) {
  	status
  }
}
```

`ladder` 는 `Boolean` 이므로 0이 될 수 없음
